// All factual content, no invented taglines.
window.CV = {
  name: "Ziyi Zhao",
  nickname: "Iggy",
  title: "Assistant Professor of Information Systems & Business Analytics",
  institution: "College of Business, Florida International University",
  location: "Miami, FL",
  email: "ziyzhao@fiu.edu",

  research: {
    topics: [
      { group: "AI", items: ["AI", "Generative AI", "Agentic AI"] },
      { group: "AI in Future of Work", items: ["Coding", "Search", "Healthcare"] },
      { group: "AI Index & Methods", items: [] },
    ],
    methods: [
      { group: "Mixed Methods", items: ["Experiments", "Econometrics", "Survey"] },
      { group: "Computational", items: ["Machine Learning", "Text Mining", "Sequence Modeling"] },
      { group: "Theory", items: ["Computational Theory Construction"] },
    ],
  },

  workingPapers: [
    {
      id: "decoding",
      authors: "Zhao, Z., Cho, K., Aaltonen, A., & Straub, D.",
      title: "Decoding Coding Advice: Evaluating Out-of-the-Box Solutions from Generative AI",
      status: "Under Revision · 3rd Round Review",
      venue: "MIS Quarterly",
      presented: ["INFORMS 2024", "AOM 2024", "IC2S2 2024", "SCECR 2023", "Harvard Business School 2023"],
    },
    {
      id: "killtwo",
      authors: "Zhao, Z., Aaltonen, A., & Pang, M.S.",
      title: "Kill Two Birds with One Stone: Using Cross-Platform Software Development Kits for Digital Innovations",
      status: "Under Review",
      venue: "Management Science",
      presented: ["AOM 2025", "BU PlatStrat 2024", "EU-DPRN 2024", "ICIS 2023", "AMCIS 2023 — Top 25% ERF Paper"],
    },
    {
      id: "searchas",
      authors: "Zhao, Z., Shan, G., Jung, J., & Wattal, S.",
      title: "Search As Me, With Me, For Me: How AI Search Modalities and Behavioral Visibility Shape Knowledge Work?",
      status: "Under Review",
      venue: "MIS Quarterly",
      presented: ["AMCIS 2025 — Best ERF Paper"],
    },
    {
      id: "infocomp",
      authors: "Scheepers, R., Zhao, Z., & Straub, D.",
      title: "Information-Based Competitiveness in the Digital Era: A Theory of Digital Information Asymmetries",
      status: "Under Review",
      venue: "Information Systems Research",
      presented: ["AOM 2025"],
    },
    {
      id: "primingai",
      authors: "Straub, D., Mandviwalla, M., & Zhao, Z.",
      title: "Priming Firms for Effective AI Use: Automating, Informating, and Autonomating and the Productivity Paradox 2.0",
      status: "Under Review",
      venue: "MIS Quarterly",
      presented: ["AOM 2025", "Advanced Practices Council, SIM 2025"],
    },
  ],

  inProgress: [
    {
      id: "invisible",
      authors: "Zhao, Z., Cho, K., Aaltonen, A., & Straub, D.",
      title: "Making the Invisible Visible: Computational Process Tracing of Human-GenAI Collaboration",
      presented: ["INFORMS 2025", "INFORMS Data Science 2025", "NYU AI Workshop 2025", "Wharton AI and the Future of Work 2025", "DSI 2026"],
    },
    {
      id: "vibecoding",
      authors: "Boussioux, L., Zhao, Z., Cho, K.",
      title: "When Code Writes the Coder: The Validation Paradox of Vibe Coding",
      presented: ["Wharton AI and the Future of Work 2026", "AOM 2026", "INFORMS 2026", "DSI 2026"],
    },
    {
      id: "generativity",
      authors: "Boussioux, L., Zhao, Z., Cho, K.",
      title: "The Anatomy of a Skill: Triple-Interface Design and the Structural Determinants of Agentic-Artifact Adoption",
      presented: ["Wharton AI and the Future of Work 2026", "SCECR 2026", "INFORMS 2026"],
    },
    {
      id: "timing",
      authors: "Yang, R., Zhao, Z., Cho, K., & Ayabakan, S.",
      title: "Timing Matters: AI Response Time in Healthcare Decision-Making",
      presented: ["ICIS 2025", "CHITA 2026", "INFORMS 2026"],
    },
    {
      id: "ambient",
      authors: "Hertelendy, A., Zhao, Z., Cho, K., & Li, J.",
      title: "When Does Ambient AI Save Time? The Verification Tax in Accountable Clinical Documentation",
      presented: ["DSI 2026", "INFORMS 2026"],
    },
  ],

  published: [
    {
      id: "digitaldriven",
      authors: "Zhao, Z., Hönigsberg, S., & Mandviwalla, M.",
      year: "2025",
      title: "Digital Driven Success: The Digitalization Effect on SME Performance",
      venue: "Information Technology for Development, 31(4), 1090–1116",
    },
  ],

  // Presentations with geography for the map. Each has its own title.
  presentations: [
    { date: "2026-11-21", displayDate: "2026-11", venue: "Decision Sciences Institute Annual Meeting (DSI 2026)", title: "When Does Ambient AI Save Time? The Verification Tax in Accountable Clinical Documentation", authors: "Hertelendy, Zhao*, Cho, Li", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-21", displayDate: "2026-11", venue: "Decision Sciences Institute Annual Meeting (DSI 2026)", title: "Making the Invisible Visible: Computational Process Tracing of Human-GenAI Collaboration", authors: "Zhao*, Cho, Aaltonen, Straub", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-21", displayDate: "2026-11", venue: "Decision Sciences Institute Annual Meeting (DSI 2026)", title: "When Code Writes the Coder: The Validation Paradox of Vibe Coding", authors: "Boussioux*, Zhao, Cho", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-08", displayDate: "2026-11", venue: "INFORMS Annual Meeting 2026", title: "When Does Ambient AI Save Time? The Verification Tax in Accountable Clinical Documentation", authors: "Hertelendy*, Zhao, Cho, Li", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-08", displayDate: "2026-11", venue: "INFORMS Annual Meeting 2026", title: "When Code Writes the Coder: The Validation Paradox of Vibe Coding", authors: "Boussioux*, Zhao, Cho", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-08", displayDate: "2026-11", venue: "INFORMS Annual Meeting 2026", title: "Timing Matters: AI Response Time in Healthcare Decision-Making", authors: "Yang*, Zhao, Cho, Ayabakan", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-11-08", displayDate: "2026-11", venue: "INFORMS Annual Meeting 2026", title: "The Anatomy of a Skill: Triple-Interface Design and the Structural Determinants of Agentic-Artifact Adoption", authors: "Boussioux*, Zhao, Cho", city: "San Francisco, CA", lat: 37.77, lng: -122.42 },
    { date: "2026-06", venue: "Statistical Challenges in eCommerce Research (SCECR 2026)", title: "The Anatomy of a Skill: Triple-Interface Design and the Structural Determinants of Agentic-Artifact Adoption", authors: "Boussioux, Zhao, Cho*", city: "Tokyo, Japan", lat: 35.68, lng: 139.69 },
    { date: "2026-07", venue: "Academy of Management Annual Meeting (AOM 2026)", title: "When Code Writes the Coder: The Validation Paradox of Vibe Coding", authors: "Boussioux, Zhao*, Cho", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2026-05", venue: "Wharton AI and the Future of Work Conference", title: "When Code Writes the Coder: The Validation Paradox of Vibe Coding", authors: "Boussioux, Zhao, Cho*", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2026-05", venue: "Wharton AI and the Future of Work Conference", title: "The Anatomy of a Skill: Triple-Interface Design and the Structural Determinants of Agentic-Artifact Adoption", authors: "Boussioux, Zhao, Cho*", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2026-05", venue: "Conference on Health IT and Analytics (CHITA)", title: "How Response Time Shapes Patient Decision-Making Using Generative AI–Based Health Agent", authors: "Yang*, Zhao, Cho, Ayabakan", city: "Washington, D.C.", lat: 38.9, lng: -77.04 },
    { date: "2026-05", venue: "Workshop “Theorizing Data and AI”", title: "How Knowledge Workers Create and Evaluate Solutions Coming from Generative Artificial Intelligence", authors: "Zhao, Cho, Aaltonen*, Straub", city: "London, UK", lat: 51.5, lng: -0.12 },
    { date: "2025-12", venue: "International Conference on Information Systems (ICIS 2025)", title: "Timing Matters: AI Response Time in Healthcare Decision-Making — TREO Talk", authors: "Yang*, Zhao, Cho, Ayabakan", city: "Nashville, TN", lat: 36.16, lng: -86.78 },
    { date: "2025-10", venue: "INFORMS Annual Meeting 2025", title: "Charting the Unseen: Uncovering the Dynamic Processes Underlying Human-GenAI Interaction in Complex Problem Solving", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Atlanta, GA", lat: 33.75, lng: -84.39 },
    { date: "2025-10", venue: "INFORMS Workshop on Data Science", title: "Making the Invisible Visible: Computational Process Tracing of Human-GenAI Collaboration", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Atlanta, GA", lat: 33.75, lng: -84.39 },
    { date: "2025-09", venue: "AI and Collaborative Innovation Workshop, NYU", title: "Making the Invisible Visible: Dynamic Process Tracing of GenAI Collaboration", authors: "Zhao*, Cho, Aaltonen, Straub", city: "New York, NY", lat: 40.71, lng: -74.0 },
    { date: "2025-08", venue: "Americas Conference on Information Systems (AMCIS 2025)", title: "Shortcuts or Blind Spots? The Impact of Search Generative Experience (SGE) on Information-Searching", authors: "Zhao*, Shan, Wattal", city: "Montréal, Canada", lat: 45.5, lng: -73.57 },
    { date: "2025-07", venue: "Academy of Management Annual Meeting (AOM 2025)", title: "Kill Two Birds with One Stone: Using Cross-Platform Software Development Kits for Digital Innovations", authors: "Zhao*, Aaltonen", city: "Copenhagen, Denmark", lat: 55.68, lng: 12.57 },
    { date: "2025-07", venue: "Academy of Management Annual Meeting (AOM 2025)", title: "Information-Based Competitiveness in the Digital Era: A Theory of Digital Information Asymmetries", authors: "Scheepers, Zhao*, Straub", city: "Copenhagen, Denmark", lat: 55.68, lng: 12.57 },
    { date: "2025-07", venue: "Academy of Management Annual Meeting (AOM 2025)", title: "From Scientific Management to AI: Predicting Opportunity and Measuring Results in the Next Wave of Automation", authors: "Mandviwalla, Straub, Zhao*", city: "Copenhagen, Denmark", lat: 55.68, lng: 12.57 },
    { date: "2025-05", venue: "Wharton AI and the Future of Work Conference", title: "Revolutionizing Workplace Problem-Solving: Collaboration with Out-of-the-Box AI Solutions", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2025-04", venue: "Fintech and Financial Institutions Research Conference", title: "Put Your Money Where Your Mouth Is: Financial Stakes and Cognitive Biases on Decentralized Prediction Markets", authors: "Zhao*", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2024-12", venue: "International Conference on Information Systems (ICIS 2024) — SIG SVC", title: "Screen Tracking of Research Engagement (STORE) in the Era of Generative AI", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Bangkok, Thailand", lat: 13.75, lng: 100.5 },
    { date: "2024-12", venue: "International Conference on Information Systems (ICIS 2024) — SIG DITE PDW", title: "Kill Two Birds with One Stone: Leveraging Multihoming Boundary Resources for Mobile App Development", authors: "Zhao*, Aaltonen", city: "Bangkok, Thailand", lat: 13.75, lng: 100.5 },
    { date: "2024-12", venue: "International Conference on Information Systems (ICIS 2024) — SIG SVC", title: "Generative AI Transparency and Predictability: A case study at Scholastic Inc.", authors: "Baumann, Wang, Chacko, Zhao*, Mandviwalla, Sankaran", city: "Bangkok, Thailand", lat: 13.75, lng: 100.5 },
    { date: "2024-10", venue: "INFORMS Annual Meeting 2024", title: "Decoding Coding Advice: Generative AI is Thinking Outside The Box in Problem-Solving", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Seattle, WA", lat: 47.6, lng: -122.33 },
    { date: "2024-08", venue: "Academy of Management Annual Meeting (AOM 2024)", title: "Decoding Coding Advice: How Credible Are Programming Solutions Produced by Generative AI?", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Chicago, IL", lat: 41.88, lng: -87.63 },
    { date: "2024-07", venue: "Platform Strategy Research Symposium (PlatStrat 2024)", title: "Kill Two Birds with One Stone: Leveraging Multihoming Boundary Resources for Mobile App Development", authors: "Zhao*, Aaltonen", city: "Boston, MA", lat: 42.36, lng: -71.06 },
    { date: "2024-07", venue: "International Conference on Computational Social Science (IC2S2 2024)", title: "Decoding Coding Advice: Generative AI is Thinking Outside-the-box in Programming Problem-Solving", authors: "Zhao*, Cho, Aaltonen, Straub", city: "Philadelphia, PA", lat: 39.95, lng: -75.17 },
    { date: "2024-06", venue: "European Digital Platform Research Network Summit (EU-DPRN 2024)", title: "Kill Two Birds with One Stone: Using Multihoming Boundary Resources in App Development", authors: "Zhao*, Aaltonen", city: "London, UK", lat: 51.5, lng: -0.12 },
    { date: "2024-05", venue: "CHI 2024 — Generative AI in UGC Workshop", title: "I’ve Got Your Daughter: Generative AI Boosts Deepfake-enhanced Cybercrime", authors: "Zhao*", city: "Honolulu, HI", lat: 21.31, lng: -157.86 },
    { date: "2023-12", venue: "International Conference on Information Systems (ICIS 2023)", title: "Mastering Efficiency: Leveraging Multihoming Boundary Resources For Mobile App Development", authors: "Zhao, Aaltonen*", city: "Hyderabad, India", lat: 17.38, lng: 78.49 },
    { date: "2023-08", venue: "KrAIS Summer Workshop 2023", title: "What If It Came From ChatGPT? The Moderating Role of Expertise in Programming Solution Adoption", authors: "Zhao, Cho*, Aaltonen", city: "Seoul, Korea", lat: 37.57, lng: 126.98 },
    { date: "2023-08", venue: "Americas Conference on Information Systems (AMCIS 2023)", title: "Kill Two Birds With One Stone: Using Multihoming Boundary Resources in App Development", authors: "Zhao*, Aaltonen", city: "Panama City, Panama", lat: 8.98, lng: -79.52 },
    { date: "2023-06", venue: "Statistical Challenges in Electronic Commerce Research (SCECR 2023)", title: "Decoding Coding Advice: Examining the Adoption and Perceived Quality of AI vs Human-Generated Recommendations", authors: "Zhao*, Cho, Aaltonen", city: "Bogotá, Colombia", lat: 4.71, lng: -74.07 },
    { date: "2023-06", venue: "Statistical Challenges in Electronic Commerce Research (SCECR 2023)", title: "Kill Two Birds with One Stone: Using Multihoming Boundary Resources in App Development", authors: "Zhao*, Aaltonen", city: "Bogotá, Colombia", lat: 4.71, lng: -74.07 },
    { date: "2023-05", venue: "MOM Harvard — Technological Adoption & Human-Algorithm Interaction Workshop", title: "Humans vs AI: The Impact of Source Credibility and Recommendation Quality on the Adoption of Programming Solutions", authors: "Zhao, Cho, Aaltonen*", city: "Boston, MA", lat: 42.36, lng: -71.06 },
    { date: "2023-05", venue: "LUISS — AI and emerging technologies: Beyond the hype", title: "Humans vs AI: The Impact of Source Credibility and Recommendation Quality on the Adoption of Programming Solutions", authors: "Zhao, Cho, Aaltonen*", city: "Rome, Italy", lat: 41.9, lng: 12.5 },
    { date: "2022-08", venue: "Americas Conference on Information Systems (AMCIS 2022)", title: "SME Digitization: How Do Micro, Small, And Medium-Sized Firms Digitize?", authors: "Zhao*, Havakhor, Mandviwalla", city: "Minneapolis, MN", lat: 44.98, lng: -93.27 },
    { date: "2022-06", venue: "Statistical Challenges in Electronic Commerce Research (SCECR 2022)", title: "Can Digital Permeation Explain Forward-Looking Value In Public Firms?", authors: "Zhao*, Havakhor, Schuff, Thatcher, Mandviwalla, Bhise", city: "Madrid, Spain", lat: 40.42, lng: -3.7 },
  ],

  invitedTalks: [
    { date: "02/2026", venue: "Fox School of Business, Temple University", city: "Philadelphia, PA" },
    { date: "11/2025", venue: "Stevens Institute of Technology", city: "Hoboken, NJ" },
    { date: "06/2025", venue: "Florida International University", city: "Miami, FL" },
    { date: "03/2025", venue: "MIS Distinguished Speaker Series, Temple University", city: "Philadelphia, PA" },
    { date: "02/2025", venue: "Advanced Practices Council, Society for Information Management", city: "Atlanta, GA" },
    { date: "02/2025", venue: "Interactive AI Fair, Temple University", city: "Philadelphia, PA" },
    { date: "01/2025", venue: "MIS Doctoral Seminar, University of Wisconsin-Madison", city: "Virtual" },
    { date: "11/2024", venue: "IBIT Advisory Board Meeting, Temple University", city: "Philadelphia, PA" },
    { date: "10/2024", venue: "DBA Research Colloquium, Temple University", city: "Philadelphia, PA" },
    { date: "09/2024", venue: "2nd Philadelphia Operations and Technology Day, Lehigh University", city: "Bethlehem, PA" },
    { date: "02/2024", venue: "Fox School of Business AI/ML Workshop, Temple University", city: "Philadelphia, PA" },
  ],

  education: [
    { school: "Temple University", loc: "Philadelphia, PA", degree: "Ph.D., Business\nAdministration", detail: "Concentrated in Management Information Systems", years: "2021–2025" },
    { school: "University of Connecticut", loc: "Hartford, CT", degree: "M.S., Business Analytics & Project Management", detail: "Highest GPA in program history", years: "2019–2021" },
    { school: "University of Nottingham", loc: "UK & China", degree: "B.S., International Business Economics", detail: "First-Class Honours · Ranked 3 / 334", years: "2015–2019" },
  ],

  teachingPhilosophy: 'I use a Minimal Variable Product (MVP) strategy in class to boost curiosity, confidence, and the ability to ask meaningful questions, so students can become the Most Valuable Player (MVP) at work.',

  courses: [
    {
      code: "ISM 6136",
      name: "Business Analytics Applications",
      school: "Florida International University",
      level: "MBA",
      role: "Instructor of Record & Course Designer",
      rating: "4.9 / 5.0 (n=36)",
      term: "Spring 2026",
      description: "Designed for the modern decision-maker, this course converts raw business challenges into mature, deployable solutions. MBA students leverage Python and Generative & Agentic AI for fast-track data exploration, automate technical hurdles, and deepen insight generation. Each session features hands-on activities that contribute directly to a ready-to-go business solution, ensuring technical methods remain deeply embedded in business contexts. The focus remains on how analytics informs managerial decision-making, navigates strategic trade-offs, and drives real organizational action.",
    },
    {
      code: "ISM 4421",
      name: "Artificial Intelligence for Business",
      school: "Florida International University",
      level: "Undergraduate",
      role: "Instructor of Record & Course Designer",
      rating: "4.9 / 5.0 (n=40)",
      term: "Spring 2026",
      description: "This class is designed for future business leaders to master Generative & Agentic AI in multi-dimensional business applications. The curriculum includes three stages: The Builder, where students engineer prompt frameworks and use vibe coding tools to build functional prototypes and Generative UIs; The Operator, which focuses on deploying deep research agents, AI solvers, and automation logic to optimize real-world workflows like supply chain, marketing, and human resources; and The Executive, where the focus shifts to governance and strategic ROI. Ultimately, the project is a \"Grand Assembly\"—a fully integrated, functioning AI solution where students merge their weekly modular builds into a cohesive product backed by a professional implementation roadmap.",
    },
    {
      code: "MIS 0855",
      name: "Data Science",
      school: "Temple University",
      level: "Undergraduate",
      role: "Instructor of Record (Fall 2024); Teaching Assistant (Fall 2023, Spring 2024)",
      rating: "4.9 / 5.0 (n=40)",
      term: "Fall 2024",
      description: "This GenEd undergraduate course covers Big Data Analytics, Visualisation, the Fundamentals of Hadoop and MapReduce, Machine Learning, and Generative AI. The class intensively uses Tableau, for which I am a Tableau Desktop Specialist, awarded by Tableau in 2020.",
    },
    {
      code: "OPIM 5604",
      name: "Predictive Modeling",
      school: "University of Connecticut",
      level: "Graduate",
      role: "Teaching Assistant (Spring 2020, Fall 2020, Spring 2021)",
      term: "2020–2021",
      description: "A required course for the Master of Business Analytics and Project Management at UConn. The course covers Machine Learning models and techniques using JMP Pro. Worked as a TA for three consecutive semesters with experience in face-to-face and online teaching and advising.",
    },
    {
      code: "OPIM 5603",
      name: "Statistics in Business Analytics",
      school: "University of Connecticut",
      level: "Graduate",
      role: "Teaching Assistant (Spring 2020, Fall 2020, Spring 2021)",
      term: "2020–2021",
      description: "A required course for the Master of Business Analytics and Project Management at UConn. The course covers Statistics using the R programming language. Students range in age from 20s to 70s. Worked as a TA for three consecutive semesters with experience in face-to-face and online teaching and advising.",
    },
  ],

  honors: {
    researchHonors: [
      "Outstanding Editor, Information Technology for Development, Awarded by AIS (2026)",
      "Junior Faculty Consortium Fellow, AOM CTO Division (2026)",
      "AIS Distinguished Member (2026)",
      "Best ERF Paper Award, AMCIS (2025)",
      "MIS Quarterly Author Development Workshop Selected Attendee (2024)",
      "MIS Quarterly Reviewer Development Workshop Selected Attendee (2024, 2025)",
      "Doctoral Consortium Fellow, AMCIS (2025)",
      "Doctoral Consortium Fellow, AOM CTO Division (2024, 2025)",
      "Doctoral Consortium Fellow, BU Platform Strategy Research Symposium (2024)",
      "Doctoral Consortium Fellow, European Digital Platform Research Network (2024)",
      "Top 25% ERF Paper, AMCIS (2023)",
    ],
    researchGrants: [
      "Google Vertex AI Agent Builder (2026) — $1,000",
      "Google Cloud Research Credits (2026) — $5,000",
      "Google Career Launchpad Program (2026) — $5,000",
      "AIS Entrepreneurial Innovation Fellowship, Kauffman Foundation (2025) — $6,500",
      "Advanced Practices Council of Society for Information Management (2025) — $5,000",
      "Syntheticusers.com Research Grant (2024) — $6,000",
      "NSF Travel Funding, Grant #2328 (2024) — $1,024",
    ],
    fiu: [
      "Dean's Office Travel Funding (2026) — $2,000",
    ],
    temple: [
      "2nd RAIS Symposium Award (2026) — $2,500",
      "IBIT Funding (2026) — $1,000",
      "1st RAIS Symposium Award (2025) — $4,000",
      "RECAP Award (2025) — $1,200",
      "1st Place, PhD Student Research Competition, Fox School of Business (2024)",
      "People's Choice, PhD Student Research Competition, Fox School of Business (2024)",
      "IBIT Funding (2024) — $5,000",
      "27th Young Scholars Interdisciplinary Funding (2023) — $3,500",
      "26th Young Scholars Interdisciplinary Funding (2023) — $2,500",
      "25th Young Scholars Interdisciplinary Funding (2022) — $1,800",
      "24th Young Scholars Interdisciplinary Funding (2022) — $1,250",
    ],
    uconn: [
      "Nominee for the Graduate Hall of Fame (2021)",
      "2021 Spring Scholarship (Top 1 academic performance) — $2,925",
      "2020 Spring Scholarship (Top 1 academic performance) — $2,925",
      "2020 Grace Hopper Celebration of Women in Computing Scholarship — $449",
    ],
    nottingham: [
      "Inspirational Women Awards (Only Student Awardee) (2019)",
      "Outstanding Graduate Awards (2019)",
      "Provost's Scholarship (2019) — $2,150",
      "Provincial Scholarship (2018) — $850",
      "Outstanding Student Awards (2017, 2018)",
      "Dean's Scholarship (2017, 2018) — $850",
    ],
    certificates: [
      "AIS SIGDITE PhD Research Seminar on Digital Innovation (2025)",
      "Online Teaching Certificate, Fox School of Business (2025)",
      "Certified Reviewer for Information Technology for Development (2024)",
      "Certified Peer Reviewer for Elsevier (2024)",
      "PhD Teaching Academy, Fox School of Business (2023)",
      "Certified Tableau Desktop Specialist (2020)",
    ],
    other: [
      "1st Place, Institute of Chartered Accountants in England and Wales Business Competition (2019)",
      "Achievement Award, Research for Digital Transformation, Peking University (2018)",
      "Outstanding Volunteer, 3rd Global SME Summit, Global Alliance of SMEs (2017)",
    ],
    media: [
      "AIS Member Spotlight",
      "AIS InSider — Jan 1, 2026",
      "AIS InSider — Oct 16, 2025",
      "AIS InSider — Aug 21, 2025",
      "AIS InSider — Nov 6, 2024",
      "The Fox Brief — July 25, 2025",
      "Substack (Levendis, 2026)",
    ],
  },

  service: {
    committee: [
      "Associate Editor, From Generative AI to Agentic IS, WI 2026",
      "Session Chair, AI/ML In Decision Making, DSI Annual Conference 2026",
      "Program Committee, Annual Workshop on Information Technologies and Systems 2026",
      "Symposium Organizer, Academy of Management Annual Meeting 2025",
      "Editorial Review Board, Information Technology for Development (since 2025)",
      "Committee Member, INFORMS Workshop on Data Science 2025",
      "Committee Member, International Conference on Computational Social Science 2024",
      "Committee Member, KrAIS Summer Workshop 2023",
    ],
    // Ordered by prestige; per-venue counts retained but no longer displayed.
    journalReviewer: [
      { name: "MIS Quarterly", count: 1 },
      { name: "Information Systems Research", count: 3 },
      { name: "Journal of the Association for Information Systems", count: 1 },
      { name: "Production and Operations Management", count: 1 },
      { name: "ACM Transactions on Management Information Systems", count: 2 },
      { name: "Internet Research", count: 15 },
      { name: "Electronic Markets", count: 2 },
      { name: "Journal of Business Research", count: 1 },
      { name: "Information Technology for Development", count: 49 },
      { name: "Industrial Management & Data Systems", count: 4 },
    ],
    journalTotal: 79,
    // Ordered by prestige; per-venue counts retained but no longer displayed.
    conferenceReviewer: [
      { name: "International Conference on Information Systems (ICIS)", count: 24 },
      { name: "Academy of Management Annual Meeting (AOM)", count: 13 },
      { name: "European Conference on Information Systems (ECIS)", count: 2 },
      { name: "Pacific Asia Conference on Information Systems (PACIS)", count: 2 },
      { name: "Americas Conference on Information Systems (AMCIS)", count: 4 },
      { name: "Hawaii International Conference on System Sciences (HICSS)", count: 2 },
      { name: "International AAAI Conference on Web and Social Media (ICWSM)", count: 1 },
      { name: "International Conference on Computational Social Science (IC2S2)", count: 9 },
      { name: "Workshop on Information Technologies and Systems (WITS)", count: 2 },
      { name: "Conference on Information Systems and Technology (CIST)", count: 1 },
      { name: "International Conference on Wirtschaftsinformatik (WI)", count: 3 },
      { name: "INFORMS Workshop on Data Science (WDS)", count: 3 },
      { name: "Korea Artificial Intelligence Society Workshop (KrAIS)", count: 2 },
      { name: "DIGI+ Postdoctoral Fellowship", count: 3 },
    ],
    conferenceTotal: 75,
    community: [
      "Mentor, AIS SIG DITE Career Mentorship Program",
      "MIS Quarterly Insider Interviewer",
      "Volunteer, ICIS 2021, 2022, 2024",
      "Volunteer, AMCIS 2022",
      "Mentor, ATOM × AIS Technology Innovation 2026 Challenge (FIU)",
    ],
  },
};
